USE CONSTRUCTION;

DESC ADDRESS;
DESC ADMIN;
DESC BASIC_DETAILS;
DESC BUILDER;
DESC BUILDER_REVIEW;
DESC COMPANY;
DESC PROJECT_DETAILS;
DESC CONTACT_DETAILS;
DESC CUSTOMER;
DESC PROJECT;

drop database construction;
